# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [ ]:
s.splite()

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [ ]:
print("the diameatr of {} kilometers."format(planet,diameter))

In [ ]:
parint(txt.format(value=12742))

## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:
d['k1'][3]['tricky'][3]['target'][3]

# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [ ]:
array=np.zeros(10)

In [ ]:
print("An Array of 10 zeros:")

In [ ]:
print(Array)

In [ ]:
array=np.fives(10)

In [ ]:
print("An Array of 10 fives:")

In [ ]:
print(Array)

## 5. Create an array of all the even integers from 20 to 35

In [ ]:
import numpy as np

In [ ]:
array=np.arange(20,35)

In [ ]:
print(array)

In [ ]:
print("Array of all the even integers form 20 to 35")

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
import numpy as np

In [ ]:
x = np.arange(0,8).reshape(3,3)

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
a = np.array([[1,2,3]])

In [ ]:
b = np.array([[4,5,6]])

In [ ]:
np.concatenate(a,b),axis=0)

In [ ]:
array([1,2])

In [ ]:
      [2,3]

In [ ]:
      [5,6]

In [ ]:
np.concatenate((a,b.T), axis1)

In [ ]:
array([1,2,3],

In [ ]:
      [4,5,6])

In [ ]:
np.concatenate((a,b);axis=None)

In [ ]:
array([1,2,3,4,5,6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [ ]:
df =pd.DataFrame(rows, colums=['3,2'])

In [ ]:
print(df)

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
select min(1st jan 2023)start_date,

In [ ]:
       max(10th Feb 2023)end_date, 

In [ ]:
from   co.orders

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:
# import pandas as pd

In [ ]:
  import pandas as pd

In [ ]:
# list

In [ ]:
list = [[1, 'aaa', 22'], [2, 'bbb', 25'], [3, 'ccc, 24]]

In [ ]:
# creating of object with colums specified

In [ ]:
df = pd.DateFrame(1st, colums=['NO', 'Name', 'Id]')

In [ ]:
print(df)